### ISSUE TITLE
Example and documentation corrections

### ISSUE THREAD

**Issue by rjlupinek** [GSA/grace-cloudcustodian#11]
Thanks for making this great module.
We have started consuming it for the ODP team, and we have a few suggestions for documentation and example completeness.

Additions to example:

* We felt that including an example for creating the s3 bucket would be helpful as it is required
* **kms_key_arn** is not actually used in the module but is a required input variable
* sender is a required argument without a default
* **s3_bucket** is a required argument without a default
* **project_name** is not a valid argument

```
module "grace_cc_s3_bucket" {
  source = "github.com/terraform-aws-modules/terraform-aws-s3-bucket?ref=v1.4.0"
  bucket = "odp-aws-ref-arch-grace-cc"
  acl    = "private"
  versioning = {
    enabled = false
  }
  tags   = "${var.default_tags}"
}

module "grace_cc" {
  source         = "github.com/GSA/grace-cloudcustodian"
  sender         = "${var.cc_sender}"
  s3_bucket      = "${module.grace_cc_s3_bucket.this_s3_bucket_arn}"
  kms_key_arn    = "${var.cc_kms_key_arn}"
  appenv         = "${var.appenv}"
}
```

vs 

```
module "example_grace_cc" {
  source       = "github.com/GSA/grace-cloudcustodian?ref=v0.1.0"
  appenv       = "environment"
  project_name = "your-project"
}
```

**Comment by briankfitzwater** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[GSA/grace-cloudcustodian] Example and documentation corrections (#11)](https://trello.com/c/8RifKfvi/1490-gsa-grace-cloudcustodian-example-and-documentation-corrections-11)

**Comment by rjlupinek** [comment]
Found that the documentation was missing some requirements ( at least if you are using the Terraform provided images ):

We had to add this to our CircleCI code when using the `hashicorp/terraform:latest` image.

```
apk add --update py-pip py3-pip zip
pip install --user virtualenv
ln -s /root/.local/bin/virtualenv /usr/bin/virtualenv
```

**Comment by briankfitzwater** [comment]
I thought the new version of Python3 included PIP. And virtualenv is available as a package, which handles the symbolic link/installation.

```
apk add --update python3 py3-virtualenv
```

Turns out neither the S3 bucket or KMS key are required any more, so I've removed those from the README and variables.tf file.  @edryan04 is updating the diagram.  See branch: [issue_11](https://github.com/GSA/grace-cloudcustodian/tree/issue_11)

**Comment by rjlupinek** [comment]
Testing in our CI now.

**Comment by briankfitzwater** [comment]
@rjlupinek How did the testing go?  I'd like to close this before end of this sprint.

**Comment by briankfitzwater** [comment]
@rjlupinek I'm going to go ahead and close this issue.  If something comes up in your testing, either open a new issue or re-open this one as appropriate.
